import 'dart:convert';

class ResponseData {
  static final String liveMatches = jsonEncode({
    "typeMatches": [
      {
        "matchType": "International",
        "seriesMatches": [
          {
            "seriesAdWrapper": {
              "seriesId": 9629,
              "seriesName": "West Indies tour of India, 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 117359,
                    "seriesId": 9629,
                    "seriesName": "West Indies tour of India, 2025",
                    "matchDesc": "1st Test",
                    "matchFormat": "TEST",
                    "startDate": "1759377600000",
                    "endDate": "1759748400000",
                    "state": "Complete",
                    "status": "India won by an innings and 140 runs",
                    "team1": {
                      "teamId": 10,
                      "teamName": "West Indies",
                      "teamSName": "WI",
                      "imageId": 172124,
                    },
                    "team2": {
                      "teamId": 2,
                      "teamName": "India",
                      "teamSName": "IND",
                      "imageId": 719031,
                    },
                    "venueInfo": {
                      "id": 50,
                      "ground": "Narendra Modi Stadium",
                      "city": "Ahmedabad",
                      "timezone": "+05:30",
                      "latitude": "23.091785",
                      "longitude": "72.597465",
                    },
                    "currBatTeamId": 2,
                    "seriesStartDt": "1759363200000",
                    "seriesEndDt": "1760572800000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Complete",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 162,
                        "wickets": 10,
                        "overs": 44.1,
                      },
                      "inngs2": {
                        "inningsId": 3,
                        "runs": 146,
                        "wickets": 10,
                        "overs": 45.1,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 448,
                        "wickets": 5,
                        "overs": 127.6,
                        "isDeclared": true,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "seriesAdWrapper": {
              "seriesId": 10201,
              "seriesName": "Australia tour of New Zealand, 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 122528,
                    "seriesId": 10201,
                    "seriesName": "Australia tour of New Zealand, 2025",
                    "matchDesc": "3rd T20I",
                    "matchFormat": "T20",
                    "startDate": "1759558500000",
                    "endDate": "1759571100000",
                    "state": "In Progress",
                    "status": "Australia need 23 runs in 26 balls",
                    "team1": {
                      "teamId": 13,
                      "teamName": "New Zealand",
                      "teamSName": "NZ",
                      "imageId": 767661,
                    },
                    "team2": {
                      "teamId": 4,
                      "teamName": "Australia",
                      "teamSName": "AUS",
                      "imageId": 172117,
                    },
                    "venueInfo": {
                      "id": 393,
                      "ground": "Bay Oval",
                      "city": "Mount Maunganui",
                      "timezone": "+13:00",
                      "latitude": "-37.670300",
                      "longitude": "176.212006",
                    },
                    "currBatTeamId": 4,
                    "seriesStartDt": "1759276800000",
                    "seriesEndDt": "1759708800000",
                    "isTimeAnnounced": true,
                    "stateTitle": "In Progress",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 156,
                        "wickets": 9,
                        "overs": 19.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 134,
                        "wickets": 7,
                        "overs": 15.4,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "seriesAdWrapper": {
              "seriesId": 10944,
              "seriesName": "ICC Mens T20 World Cup Africa Regional Final 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 134903,
                    "seriesId": 10944,
                    "seriesName":
                        "ICC Mens T20 World Cup Africa Regional Final 2025",
                    "matchDesc": "7th Place Play-off",
                    "matchFormat": "T20",
                    "startDate": "1759563000000",
                    "endDate": "1759575600000",
                    "state": "In Progress",
                    "status": "Botswana need 126 runs",
                    "team1": {
                      "teamId": 553,
                      "teamName": "Malawi",
                      "teamSName": "MWI",
                      "imageId": 172605,
                    },
                    "team2": {
                      "teamId": 529,
                      "teamName": "Botswana",
                      "teamSName": "BW",
                      "imageId": 172579,
                    },
                    "venueInfo": {
                      "id": 762,
                      "ground": "Takashinga Sports Club",
                      "city": "Harare",
                      "timezone": "+02:00",
                      "latitude": "-17.88849",
                      "longitude": "30.99021",
                    },
                    "currBatTeamId": 529,
                    "seriesStartDt": "1758844800000",
                    "seriesEndDt": "1759708800000",
                    "isTimeAnnounced": true,
                    "stateTitle": "In Progress",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 151,
                        "wickets": 5,
                        "overs": 19.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {"inningsId": 2, "runs": 26, "overs": 3.6},
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 134892,
                    "seriesId": 10944,
                    "seriesName":
                        "ICC Mens T20 World Cup Africa Regional Final 2025",
                    "matchDesc": "3rd Place Play-off",
                    "matchFormat": "T20",
                    "startDate": "1759563000000",
                    "endDate": "1759575600000",
                    "state": "In Progress",
                    "status": "Tanzania need 101 runs in 66 balls",
                    "team1": {
                      "teamId": 14,
                      "teamName": "Kenya",
                      "teamSName": "KEN",
                      "imageId": 172129,
                    },
                    "team2": {
                      "teamId": 535,
                      "teamName": "Tanzania",
                      "teamSName": "TAN",
                      "imageId": 172586,
                    },
                    "venueInfo": {
                      "id": 69,
                      "ground": "Harare Sports Club",
                      "city": "Harare",
                      "timezone": "+02:00",
                      "latitude": "-17.814114",
                      "longitude": "31.050962",
                    },
                    "currBatTeamId": 535,
                    "seriesStartDt": "1758844800000",
                    "seriesEndDt": "1759708800000",
                    "isTimeAnnounced": true,
                    "stateTitle": "In Progress",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 142,
                        "wickets": 7,
                        "overs": 19.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 42,
                        "wickets": 4,
                        "overs": 8.6,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "ad": {
              "name": "native_matches",
              "layout": "native_large",
              "position": 3,
            },
          },
        ],
      },
      {
        "matchType": "Domestic",
        "seriesMatches": [
          {
            "seriesAdWrapper": {
              "seriesId": 10823,
              "seriesName": "Sheffield Shield 2025-26",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 133209,
                    "seriesId": 10823,
                    "seriesName": "Sheffield Shield 2025-26",
                    "matchDesc": "2nd Match",
                    "matchFormat": "TEST",
                    "startDate": "1759537800000",
                    "endDate": "1759822200000",
                    "state": "Stumps",
                    "status": "Day 1: Stumps",
                    "team1": {
                      "teamId": 158,
                      "teamName": "South Australia",
                      "teamSName": "SAUS",
                      "imageId": 172225,
                    },
                    "team2": {
                      "teamId": 52,
                      "teamName": "Victoria",
                      "teamSName": "VIC",
                      "imageId": 172153,
                    },
                    "venueInfo": {
                      "id": 40,
                      "ground": "Adelaide Oval",
                      "city": "Adelaide",
                      "timezone": "+10:30",
                      "latitude": "-34.915516",
                      "longitude": "138.596115",
                    },
                    "currBatTeamId": 158,
                    "seriesStartDt": "1759536000000",
                    "seriesEndDt": "1774915200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 270,
                        "wickets": 3,
                        "overs": 93.6,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133220,
                    "seriesId": 10823,
                    "seriesName": "Sheffield Shield 2025-26",
                    "matchDesc": "3rd Match",
                    "matchFormat": "TEST",
                    "startDate": "1759545000000",
                    "endDate": "1759829400000",
                    "state": "Stumps",
                    "status": "Day 1: Stumps",
                    "team1": {
                      "teamId": 104,
                      "teamName": "New South Wales",
                      "teamSName": "NSW",
                      "imageId": 172196,
                    },
                    "team2": {
                      "teamId": 87,
                      "teamName": "Western Australia",
                      "teamSName": "WA",
                      "imageId": 172180,
                    },
                    "venueInfo": {
                      "id": 38,
                      "ground": "W.A.C.A. Ground",
                      "city": "Perth",
                      "timezone": "+08:00",
                      "latitude": "-31.959806",
                      "longitude": "115.879585",
                    },
                    "currBatTeamId": 104,
                    "seriesStartDt": "1759536000000",
                    "seriesEndDt": "1774915200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 35,
                        "wickets": 3,
                        "overs": 25.1,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133198,
                    "seriesId": 10823,
                    "seriesName": "Sheffield Shield 2025-26",
                    "matchDesc": "1st Match",
                    "matchFormat": "TEST",
                    "startDate": "1759536000000",
                    "endDate": "1759820400000",
                    "state": "Stumps",
                    "status": "Day 1: Stumps",
                    "team1": {
                      "teamId": 166,
                      "teamName": "Tasmania",
                      "teamSName": "TAS",
                      "imageId": 172235,
                    },
                    "team2": {
                      "teamId": 164,
                      "teamName": "Queensland",
                      "teamSName": "QL",
                      "imageId": 172233,
                    },
                    "venueInfo": {
                      "id": 300,
                      "ground": "Allan Border Field",
                      "city": "Brisbane",
                      "timezone": "+10:00",
                      "latitude": "-27.435145",
                      "longitude": "153.046143",
                    },
                    "currBatTeamId": 166,
                    "seriesStartDt": "1759536000000",
                    "seriesEndDt": "1774915200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 299,
                        "wickets": 6,
                        "overs": 91.6,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "seriesAdWrapper": {
              "seriesId": 10300,
              "seriesName": "Irani Cup 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 123650,
                    "seriesId": 10300,
                    "seriesName": "Irani Cup 2025",
                    "matchDesc": "Irani Cup",
                    "matchFormat": "TEST",
                    "startDate": "1759291200000",
                    "endDate": "1759662000000",
                    "state": "Innings Break",
                    "status":
                        "Day 4: Innings Break - Vidarbha lead by 360 runs",
                    "team1": {
                      "teamId": 248,
                      "teamName": "Vidarbha",
                      "teamSName": "VID",
                      "imageId": 172301,
                    },
                    "team2": {
                      "teamId": 82,
                      "teamName": "Rest of India",
                      "teamSName": "ROI",
                      "imageId": 172176,
                    },
                    "venueInfo": {
                      "id": 228,
                      "ground": "Vidarbha Cricket Association Stadium",
                      "city": "Nagpur",
                      "timezone": "+05:30",
                      "latitude": "21.013566",
                      "longitude": "79.039576",
                    },
                    "currBatTeamId": 248,
                    "seriesStartDt": "1759276800000",
                    "seriesEndDt": "1759795200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Ings Break",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 342,
                        "wickets": 10,
                        "overs": 101.4,
                      },
                      "inngs2": {
                        "inningsId": 3,
                        "runs": 232,
                        "wickets": 10,
                        "overs": 94.1,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 214,
                        "wickets": 10,
                        "overs": 69.5,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "seriesAdWrapper": {
              "seriesId": 10878,
              "seriesName": "CSA Four-Day Series Division One 2025-26",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 133886,
                    "seriesId": 10878,
                    "seriesName": "CSA Four-Day Series Division One 2025-26",
                    "matchDesc": "6th Match",
                    "matchFormat": "TEST",
                    "startDate": "1759388400000",
                    "endDate": "1759672800000",
                    "state": "Stumps",
                    "status":
                        "Day 2: Stumps - KwaZulu-Natal Inland trail by 32 runs",
                    "team1": {
                      "teamId": 155,
                      "teamName": "Warriors",
                      "teamSName": "WAR",
                      "imageId": 172222,
                    },
                    "team2": {
                      "teamId": 1766,
                      "teamName": "KwaZulu-Natal Inland",
                      "teamSName": "KZNIN",
                      "imageId": 349611,
                    },
                    "venueInfo": {
                      "id": 206,
                      "ground": "City Oval",
                      "city": "Pietermaritzburg",
                      "timezone": "+02:00",
                      "latitude": "-29.551181",
                      "longitude": "30.407238",
                    },
                    "currBatTeamId": 1766,
                    "seriesStartDt": "1758758400000",
                    "seriesEndDt": "1771891200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 140,
                        "wickets": 10,
                        "overs": 48.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 108,
                        "wickets": 6,
                        "overs": 41.6,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133875,
                    "seriesId": 10878,
                    "seriesName": "CSA Four-Day Series Division One 2025-26",
                    "matchDesc": "4th Match",
                    "matchFormat": "TEST",
                    "startDate": "1759392000000",
                    "endDate": "1759676400000",
                    "state": "Stumps",
                    "status": "Day 2: Stumps - Boland lead by 9 runs",
                    "team1": {
                      "teamId": 1759,
                      "teamName": "Boland",
                      "teamSName": "BOL",
                      "imageId": 349610,
                    },
                    "team2": {
                      "teamId": 90,
                      "teamName": "Dolphins",
                      "teamSName": "DOL",
                      "imageId": 172183,
                    },
                    "venueInfo": {
                      "id": 207,
                      "ground": "Boland Park",
                      "city": "Paarl",
                      "timezone": "+02:00",
                      "latitude": "-33.730900",
                      "longitude": "18.970760",
                    },
                    "currBatTeamId": 1759,
                    "seriesStartDt": "1758758400000",
                    "seriesEndDt": "1771891200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 156,
                        "wickets": 10,
                        "overs": 45.2,
                      },
                      "inngs2": {
                        "inningsId": 3,
                        "runs": 199,
                        "wickets": 1,
                        "overs": 47.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 346,
                        "wickets": 10,
                        "overs": 91.2,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133897,
                    "seriesId": 10878,
                    "seriesName": "CSA Four-Day Series Division One 2025-26",
                    "matchDesc": "7th Match",
                    "matchFormat": "TEST",
                    "startDate": "1759392000000",
                    "endDate": "1759676400000",
                    "state": "Stumps",
                    "status": "Day 2: Stumps - Titans trail by 338 runs",
                    "team1": {
                      "teamId": 922,
                      "teamName": "North West",
                      "teamSName": "NWEST",
                      "imageId": 248439,
                    },
                    "team2": {
                      "teamId": 89,
                      "teamName": "Titans",
                      "teamSName": "TIT",
                      "imageId": 172182,
                    },
                    "venueInfo": {
                      "id": 102,
                      "ground": "Senwes Park",
                      "city": "Potchefstroom",
                      "timezone": "+02:00",
                      "latitude": "-26.695565",
                      "longitude": "27.100691",
                    },
                    "currBatTeamId": 89,
                    "seriesStartDt": "1758758400000",
                    "seriesEndDt": "1771891200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 491,
                        "wickets": 8,
                        "overs": 133.6,
                        "isDeclared": true,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 153,
                        "wickets": 4,
                        "overs": 44.6,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133880,
                    "seriesId": 10878,
                    "seriesName": "CSA Four-Day Series Division One 2025-26",
                    "matchDesc": "5th Match",
                    "matchFormat": "TEST",
                    "startDate": "1759392000000",
                    "endDate": "1759676400000",
                    "state": "Stumps",
                    "status": "Day 2: Stumps - Lions lead by 200 runs",
                    "team1": {
                      "teamId": 917,
                      "teamName": "Western Province",
                      "teamSName": "WPR",
                      "imageId": 248460,
                    },
                    "team2": {
                      "teamId": 157,
                      "teamName": "Lions",
                      "teamSName": "LIONS",
                      "imageId": 172224,
                    },
                    "venueInfo": {
                      "id": 52,
                      "ground": "Newlands",
                      "city": "Cape Town",
                      "timezone": "+02:00",
                      "latitude": "-33.979629",
                      "longitude": "18.459466",
                    },
                    "currBatTeamId": 157,
                    "seriesStartDt": "1758758400000",
                    "seriesEndDt": "1771891200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 193,
                        "wickets": 10,
                        "overs": 44.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 393,
                        "wickets": 6,
                        "overs": 141.6,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "seriesAdWrapper": {
              "seriesId": 10911,
              "seriesName": "CSA Four-Day Series Division Two 2025-26",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 134491,
                    "seriesId": 10911,
                    "seriesName": "CSA Four-Day Series Division Two 2025-26",
                    "matchDesc": "4th Match",
                    "matchFormat": "TEST",
                    "startDate": "1759392000000",
                    "endDate": "1759676400000",
                    "state": "Stumps",
                    "status": "Day 2: Stumps - Limpopo trail by 428 runs",
                    "team1": {
                      "teamId": 1768,
                      "teamName": "South Western Districts",
                      "teamSName": "SWD",
                      "imageId": 349609,
                    },
                    "team2": {
                      "teamId": 912,
                      "teamName": "Limpopo",
                      "teamSName": "LIMPO",
                      "imageId": 248430,
                    },
                    "venueInfo": {
                      "id": 772,
                      "ground": "Polokwane Cricket Club",
                      "city": "Polokwane",
                      "timezone": "+02:00",
                      "latitude": "-23.912260",
                      "longitude": "29.453550",
                    },
                    "currBatTeamId": 912,
                    "seriesStartDt": "1758758400000",
                    "seriesEndDt": "1770854400000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 490,
                        "wickets": 10,
                        "overs": 156.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 62,
                        "wickets": 2,
                        "overs": 23.6,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 134485,
                    "seriesId": 10911,
                    "seriesName": "CSA Four-Day Series Division Two 2025-26",
                    "matchDesc": "3rd Match",
                    "matchFormat": "TEST",
                    "startDate": "1759392000000",
                    "endDate": "1759676400000",
                    "state": "Stumps",
                    "status": "Day 2: Stumps - Northern Cape trail by 272 runs",
                    "team1": {
                      "teamId": 903,
                      "teamName": "Mpumalanga Rhinos",
                      "teamSName": "MPR",
                      "imageId": 248434,
                    },
                    "team2": {
                      "teamId": 923,
                      "teamName": "Northern Cape",
                      "teamSName": "NCAPE",
                      "imageId": 248438,
                    },
                    "venueInfo": {
                      "id": 148,
                      "ground": "Diamond Oval",
                      "city": "Kimberley",
                      "timezone": "+02:00",
                      "latitude": "-28.742487",
                      "longitude": "24.742101",
                    },
                    "currBatTeamId": 923,
                    "seriesStartDt": "1758758400000",
                    "seriesEndDt": "1770854400000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 463,
                        "wickets": 10,
                        "overs": 118.5,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 191,
                        "wickets": 7,
                        "overs": 68.6,
                      },
                    },
                  },
                },
              ],
            },
          },
        ],
      },
      {
        "matchType": "Women",
        "seriesMatches": [
          {
            "seriesAdWrapper": {
              "seriesId": 10009,
              "seriesName": "ICC Womens World Cup 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 121477,
                    "seriesId": 10009,
                    "seriesName": "ICC Womens World Cup 2025",
                    "matchDesc": "5th Match",
                    "matchFormat": "ODI",
                    "startDate": "1759570200000",
                    "endDate": "1759599000000",
                    "state": "Delay",
                    "status": "Toss delayed due to rain",
                    "team1": {
                      "teamId": 258,
                      "teamName": "Sri Lanka Women",
                      "teamSName": "SLW",
                      "imageId": 172311,
                    },
                    "team2": {
                      "teamId": 100,
                      "teamName": "Australia Women",
                      "teamSName": "AUSW",
                      "imageId": 172192,
                    },
                    "venueInfo": {
                      "id": 15,
                      "ground": "R.Premadasa Stadium",
                      "city": "Colombo",
                      "timezone": "+05:30",
                      "latitude": "6.939966",
                      "longitude": "79.872222",
                    },
                    "isTournament": true,
                    "seriesStartDt": "1759190400000",
                    "seriesEndDt": "1762214400000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Delay",
                  },
                },
              ],
            },
          },
        ],
      },
    ],
    "filters": {
      "matchType": ["International", "League", "Domestic", "Women"],
    },
    "appIndex": {
      "seoTitle": "Live Cricket Score - Scorecard and Match Results",
      "webURL": "www.cricbuzz.com/live-cricket-scores/",
    },
    "responseLastUpdated": "1759572208",
  });
  static final String scorecard = jsonEncode({
    "scorecard": [
      {
        "inningsid": 1,
        "batsman": [
          {
            "id": 11090,
            "balls": 37,
            "runs": 26,
            "fours": 5,
            "sixes": 0,
            "strkrate": "70.27",
            "name": "Saif Hassan",
            "nickname": "Saif Hassan",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c Rashid Khan b Nangeyalia Kharote",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 14205,
            "balls": 10,
            "runs": 10,
            "fours": 2,
            "sixes": 0,
            "strkrate": "100",
            "name": "Tanzid Hasan Tamim",
            "nickname": "Tanzid Hasan",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c Gurbaz b Azmatullah",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 9864,
            "balls": 5,
            "runs": 2,
            "fours": 0,
            "sixes": 0,
            "strkrate": "40",
            "name": "Najmul Hossain Shanto",
            "nickname": "Shanto",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c Shahidi b Azmatullah",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13223,
            "balls": 85,
            "runs": 56,
            "fours": 1,
            "sixes": 3,
            "strkrate": "65.88",
            "name": "Towhid Hridoy",
            "nickname": "Towhid Hridoy",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "run out (Shahidi/Gurbaz)",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11081,
            "balls": 84,
            "runs": 58,
            "fours": 1,
            "sixes": 1,
            "strkrate": "69.05",
            "name": "Mehidy Hasan Miraz",
            "nickname": "Mehidy Hasan Miraz",
            "iscaptain": true,
            "iskeeper": false,
            "outdec": "batting",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11088,
            "balls": 9,
            "runs": 9,
            "fours": 1,
            "sixes": 0,
            "strkrate": "100",
            "name": "Jaker Ali",
            "nickname": "Jaker Ali",
            "iscaptain": false,
            "iskeeper": true,
            "outdec": "batting",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 8534,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Nurul Hasan",
            "nickname": "Nurul Hasan",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 8548,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Taskin Ahmed",
            "nickname": "Taskin Ahmed",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13226,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Hasan Mahmud",
            "nickname": "Hasan Mahmud",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13260,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Tanvir Islam",
            "nickname": "Tanvir Islam",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 15274,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Tanzim Hasan Sakib",
            "nickname": "Tanzim Hasan Sakib",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
        ],
        "bowler": [
          {
            "id": 53160,
            "overs": "4",
            "maidens": 0,
            "wickets": 0,
            "runs": 25,
            "economy": "6.2",
            "name": "Bashir Ahmad",
            "nickname": "Bashir Ahmad",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 24,
            "rpb": 0.0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13214,
            "overs": "7",
            "maidens": 0,
            "wickets": 2,
            "runs": 29,
            "economy": "4.1",
            "name": "Azmatullah Omarzai",
            "nickname": "Azmatullah",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 42,
            "rpb": 0.0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 36501,
            "overs": "5",
            "maidens": 1,
            "wickets": 0,
            "runs": 27,
            "economy": "5.4",
            "name": "AM Ghazanfar",
            "nickname": "Ghazanfar",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 30,
            "rpb": 0.0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 22956,
            "overs": "10",
            "maidens": 1,
            "wickets": 1,
            "runs": 32,
            "economy": "3.2",
            "name": "Nangeyalia Kharote",
            "nickname": "Nangeyalia Kharote",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 60,
            "rpb": 0.0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 10738,
            "overs": "6",
            "maidens": 0,
            "wickets": 0,
            "runs": 25,
            "economy": "4.2",
            "name": "Rashid Khan",
            "nickname": "Rashid Khan",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 36,
            "rpb": 0.0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 3007,
            "overs": "6",
            "maidens": 0,
            "wickets": 0,
            "runs": 27,
            "economy": "4.5",
            "name": "Mohammad Nabi",
            "nickname": "Nabi",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 36,
            "rpb": 0.0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
        ],
        "fow": {
          "fow": [
            {
              "batsmanid": 14205,
              "batsmanname": "Tanzid Hasan Tamim",
              "overnbr": 3.4,
              "runs": 18,
              "ballnbr": 22,
            },
            {
              "batsmanid": 9864,
              "batsmanname": "Najmul Hossain Shanto",
              "overnbr": 5.1,
              "runs": 25,
              "ballnbr": 31,
            },
            {
              "batsmanid": 11090,
              "batsmanname": "Saif Hassan",
              "overnbr": 11.5,
              "runs": 53,
              "ballnbr": 71,
            },
            {
              "batsmanid": 13223,
              "batsmanname": "Towhid Hridoy",
              "overnbr": 35.2,
              "runs": 154,
              "ballnbr": 212,
            },
          ],
        },
        "extras": {
          "legbyes": 4,
          "byes": 0,
          "wides": 2,
          "noballs": 2,
          "penalty": 0,
          "total": 8,
        },
        "pp": {
          "powerplay": [
            {
              "id": 8,
              "ovrfrom": 0.1,
              "ovrto": 10.0,
              "pptype": "mandatory",
              "run": 51,
              "wickets": 0,
            },
          ],
        },
        "score": 169,
        "wickets": 4,
        "overs": 38.0,
        "runrate": 4.45,
        "batteamname": "Bangladesh",
        "batteamsname": "BAN",
        "isdeclared": false,
        "isfollowon": false,
        "ballnbr": 228,
        "rpb": 0.74,
        "partnership": {
          "partnership": [
            {
              "id": 0,
              "bat1id": 11090,
              "bat1name": "Saif Hassan",
              "bat1runs": 8,
              "bat1fours": 1,
              "bat1sixes": 0,
              "bat2id": 14205,
              "bat2name": "Tanzid Hasan",
              "bat2runs": 10,
              "bat2fours": 2,
              "bat2sixes": 0,
              "totalruns": 18,
              "totalballs": 22,
              "bat1balls": 12,
              "bat2balls": 10,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 2,
              "bat1twos": 1,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 1,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 1,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 2,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 11090,
              "bat1name": "Saif Hassan",
              "bat1runs": 4,
              "bat1fours": 1,
              "bat1sixes": 0,
              "bat2id": 9864,
              "bat2name": "Shanto",
              "bat2runs": 2,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 7,
              "totalballs": 9,
              "bat1balls": 4,
              "bat2balls": 5,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 1,
              "bat1sixers": 0,
              "bat2ones": 2,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 11090,
              "bat1name": "Saif Hassan",
              "bat1runs": 14,
              "bat1fours": 3,
              "bat1sixes": 0,
              "bat2id": 13223,
              "bat2name": "Towhid Hridoy",
              "bat2runs": 13,
              "bat2fours": 1,
              "bat2sixes": 1,
              "totalruns": 28,
              "totalballs": 40,
              "bat1balls": 21,
              "bat2balls": 20,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 2,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 3,
              "bat1sixers": 0,
              "bat2ones": 3,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 1,
              "bat2sixers": 1,
            },
            {
              "id": 0,
              "bat1id": 11081,
              "bat1name": "Mehidy Hasan Miraz",
              "bat1runs": 52,
              "bat1fours": 1,
              "bat1sixes": 1,
              "bat2id": 13223,
              "bat2name": "Towhid Hridoy",
              "bat2runs": 43,
              "bat2fours": 0,
              "bat2sixes": 2,
              "totalruns": 101,
              "totalballs": 141,
              "bat1balls": 77,
              "bat2balls": 65,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 26,
              "bat1twos": 8,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 1,
              "bat1sixers": 1,
              "bat2ones": 27,
              "bat2twos": 2,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 2,
            },
            {
              "id": 0,
              "bat1id": 11081,
              "bat1name": "Mehidy Hasan Miraz",
              "bat1runs": 6,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 11088,
              "bat2name": "Jaker Ali",
              "bat2runs": 9,
              "bat2fours": 1,
              "bat2sixes": 0,
              "totalruns": 15,
              "totalballs": 16,
              "bat1balls": 7,
              "bat2balls": 9,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 4,
              "bat1twos": 1,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 3,
              "bat2twos": 1,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 1,
              "bat2sixers": 0,
            },
          ],
        },
      },
    ],
    "ismatchcomplete": false,
    "appindex": {
      "seotitle":
          "Cricket scorecard - AFG vs BAN 1st ODI,Afghanistan vs Bangladesh in UAE 2025 | Cricbuzz.com",
      "weburl":
          "http://www.cricbuzz.com/live-cricket-scorecard/133671/afg-vs-ban-1st-odi-afghanistan-vs-bangladesh-in-uae-2025",
    },
    "status": "Bangladesh opt to bat",
    "responselastupdated": 1759934758,
  });

  static final String matchInfo = jsonEncode({
    "matchid": 117362,
    "seriesid": 9629,
    "seriesname": "West Indies tour of India, 2025",
    "matchdesc": "2nd Test",
    "matchformat": "TEST",
    "startdate": 1760068800000,
    "enddate": 1760439600000,
    "state": "Stumps",
    "status": "Day 2: Stumps",
    "team1": {
      "teamid": 2,
      "teamname": "India",
      "teamsname": "IND",
      "isfullmember": false,
      "isassociated": false,
      "isleagueteam": false,
      "iswomenteam": false,
      "isheader": false,
      "isactive": false,
      "teampriority": "",
      "isvideopresent": false,
      "imageid": 0,
      "countryname": "",
      "belongsto": "",
    },
    "team2": {
      "teamid": 10,
      "teamname": "West Indies",
      "teamsname": "WI",
      "isfullmember": false,
      "isassociated": false,
      "isleagueteam": false,
      "iswomenteam": false,
      "isheader": false,
      "isactive": false,
      "teampriority": "",
      "isvideopresent": false,
      "imageid": 0,
      "countryname": "",
      "belongsto": "",
    },
    "umpire1": {"id": 4730, "name": "Paul Reiffel", "country": "AUS"},
    "umpire2": {"id": 5398, "name": "Richard Illingworth", "country": "ENG"},
    "umpire3": {"id": 5475, "name": "Alex Wharf", "country": "ENG"},
    "referee": {"id": 3395, "name": "Andy Pycroft", "country": "ZIM"},
    "venueinfo": {
      "id": 51,
      "ground": "Arun Jaitley Stadium",
      "city": "Delhi",
      "country": "India",
      "timezone": "+05:30",
      "established": 1883,
      "capacity": "48000",
      "knownas": "",
      "ends": "Stadium End, Pavilion End",
      "hometeam": "Delhi, Delhi Capitals",
      "floodlights": false,
      "curator": "",
      "profile": "",
      "imageurl": "",
      "groundlength": 0.0,
      "groundwidth": 0.0,
      "othersports": "",
      "imageid": "",
      "latitude": "",
      "longitude": "",
    },
    "currbatteamid": 0,
    "ismatchnotcovered": false,
    "appindex": {
      "seotitle":
          "Cricket match facts IND vs WI 2nd Test,West Indies tour of India, 2025 | Cricbuzz.com",
      "weburl":
          "http://www.cricbuzz.com/cricket-match-facts/117362/ind-vs-wi-2nd-test-west-indies-tour-of-india-2025",
    },
    "istournament": false,
    "tossstatus": "India opt to bat",
    "seriesstartdt": 1759276800000,
    "seriesenddt": 1760486400000,
    "istimeannounced": false,
    "statetitle": "",
    "replacematchid": 0,
    "livestreamenabled": false,
    "isfantasyenabled": false,
    "broadcastinfo": [
      {
        "country": "IN",
        "broadcaster": [
          {"broadcasttype": "Streaming", "value": "JioHotstar"},
          {"broadcasttype": "TV", "value": "Star Sports Network"},
        ],
      },
    ],
    "daynight": false,
    "matchtype": "International",
    "seriestype": "",
    "shortstatus": "Stump",
    "boundarytrackervalues": {"boundarytrackervalue": []},
    "matchimageid": 769236,
    "islivestreamenabled": false,
    "isfantasyhandbookenabled": false,
  });
}
