import 'dart:convert';

class ResponseData {
  static final String liveMatches = jsonEncode({
    "typeMatches": [
      {
        "matchType": "International",
        "seriesMatches": [
          {
            "seriesAdWrapper": {
              "seriesId": 7572,
              "seriesName": "ICC Cricket World Cup League Two 2023-27",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 135261,
                    "seriesId": 7572,
                    "seriesName": "ICC Cricket World Cup League Two 2023-27",
                    "matchDesc": "88th Match",
                    "matchFormat": "ODI",
                    "startDate": "1761802200000",
                    "endDate": "1761831000000",
                    "state": "Complete",
                    "status": "United Arab Emirates won by 5 wkts",
                    "team1": {
                      "teamId": 72,
                      "teamName": "Nepal",
                      "teamSName": "NEP",
                      "imageId": 776331,
                    },
                    "team2": {
                      "teamId": 7,
                      "teamName": "United Arab Emirates",
                      "teamSName": "UAE",
                      "imageId": 776242,
                    },
                    "venueInfo": {
                      "id": 289,
                      "ground": "ICC Academy Ground",
                      "city": "Dubai",
                      "timezone": "+04:00",
                      "latitude": "25.036563",
                      "longitude": "55.227611",
                    },
                    "currBatTeamId": 7,
                    "seriesStartDt": "1707955200000",
                    "seriesEndDt": "1806537600000",
                    "isTimeAnnounced": true,
                    "stateTitle": "UAE Won",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 233,
                        "wickets": 10,
                        "overs": 49.6,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 237,
                        "wickets": 5,
                        "overs": 43.3,
                      },
                    },
                  },
                },
              ],
            },
          },
        ],
      },
      {
        "matchType": "Domestic",
        "seriesMatches": [
          {
            "seriesAdWrapper": {
              "seriesId": 9938,
              "seriesName": "South Africa A tour of India, 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 119879,
                    "seriesId": 9938,
                    "seriesName": "South Africa A tour of India, 2025",
                    "matchDesc": "1st Unofficial Test",
                    "matchFormat": "TEST",
                    "startDate": "1761796800000",
                    "endDate": "1762081200000",
                    "state": "Stumps",
                    "status": "Day 1: Stumps",
                    "team1": {
                      "teamId": 268,
                      "teamName": "South Africa A",
                      "teamSName": "RSAA",
                      "imageId": 776296,
                    },
                    "team2": {
                      "teamId": 78,
                      "teamName": "India A",
                      "teamSName": "INDA",
                      "imageId": 776181,
                    },
                    "venueInfo": {
                      "id": 1438087,
                      "ground": "BCCI Centre of Excellence Ground 1",
                      "city": "Bengaluru",
                      "timezone": "+05:30",
                      "latitude": "12.978853",
                      "longitude": "77.599533",
                    },
                    "currBatTeamId": 268,
                    "seriesStartDt": "1761782400000",
                    "seriesEndDt": "1763683200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 299,
                        "wickets": 9,
                        "overs": 85.2,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "seriesAdWrapper": {
              "seriesId": 10823,
              "seriesName": "Sheffield Shield 2025-26",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 133253,
                    "seriesId": 10823,
                    "seriesName": "Sheffield Shield 2025-26",
                    "matchDesc": "8th Match",
                    "matchFormat": "TEST",
                    "startDate": "1761609600000",
                    "endDate": "1761894000000",
                    "state": "Stumps",
                    "status": "Day 3: Stumps - Queensland trail by 191 runs",
                    "team1": {
                      "teamId": 104,
                      "teamName": "New South Wales",
                      "teamSName": "NSW",
                      "imageId": 172196,
                    },
                    "team2": {
                      "teamId": 164,
                      "teamName": "Queensland",
                      "teamSName": "QL",
                      "imageId": 172233,
                    },
                    "venueInfo": {
                      "id": 35,
                      "ground": "The Gabba",
                      "city": "Brisbane",
                      "timezone": "+10:00",
                      "latitude": "-27.485829",
                      "longitude": "153.038055",
                    },
                    "currBatTeamId": 164,
                    "seriesStartDt": "1759536000000",
                    "seriesEndDt": "1774915200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 429,
                        "wickets": 7,
                        "overs": 116.5,
                        "isDeclared": true,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 238,
                        "wickets": 4,
                        "overs": 69.6,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133259,
                    "seriesId": 10823,
                    "seriesName": "Sheffield Shield 2025-26",
                    "matchDesc": "9th Match",
                    "matchFormat": "TEST",
                    "startDate": "1761618600000",
                    "endDate": "1761903000000",
                    "state": "Stumps",
                    "status":
                        "Day 3: Stumps - South Australia lead by 205 runs",
                    "team1": {
                      "teamId": 158,
                      "teamName": "South Australia",
                      "teamSName": "SAUS",
                      "imageId": 172225,
                    },
                    "team2": {
                      "teamId": 87,
                      "teamName": "Western Australia",
                      "teamSName": "WA",
                      "imageId": 172180,
                    },
                    "venueInfo": {
                      "id": 38,
                      "ground": "W.A.C.A. Ground",
                      "city": "Perth",
                      "timezone": "+08:00",
                      "latitude": "-31.959806",
                      "longitude": "115.879585",
                    },
                    "currBatTeamId": 158,
                    "seriesStartDt": "1759536000000",
                    "seriesEndDt": "1774915200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 215,
                        "wickets": 10,
                        "overs": 58.6,
                      },
                      "inngs2": {
                        "inningsId": 3,
                        "runs": 297,
                        "wickets": 4,
                        "overs": 96.4,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 307,
                        "wickets": 10,
                        "overs": 110.2,
                      },
                    },
                  },
                },
                {
                  "matchInfo": {
                    "matchId": 133248,
                    "seriesId": 10823,
                    "seriesName": "Sheffield Shield 2025-26",
                    "matchDesc": "7th Match",
                    "matchFormat": "TEST",
                    "startDate": "1761607800000",
                    "endDate": "1761892200000",
                    "state": "Stumps",
                    "status": "Day 3: Stumps - Tasmania need 327 runs",
                    "team1": {
                      "teamId": 52,
                      "teamName": "Victoria",
                      "teamSName": "VIC",
                      "imageId": 172153,
                    },
                    "team2": {
                      "teamId": 166,
                      "teamName": "Tasmania",
                      "teamSName": "TAS",
                      "imageId": 172235,
                    },
                    "venueInfo": {
                      "id": 122,
                      "ground": "Junction Oval",
                      "city": "Melbourne",
                      "timezone": "+11:00",
                      "latitude": "-37.856007",
                      "longitude": "144.980155",
                    },
                    "currBatTeamId": 166,
                    "seriesStartDt": "1759536000000",
                    "seriesEndDt": "1774915200000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Stumps",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 256,
                        "wickets": 10,
                        "overs": 90.5,
                      },
                      "inngs2": {
                        "inningsId": 3,
                        "runs": 330,
                        "wickets": 5,
                        "overs": 96.6,
                        "isDeclared": true,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 232,
                        "wickets": 10,
                        "overs": 80.4,
                      },
                      "inngs2": {
                        "inningsId": 4,
                        "runs": 28,
                        "wickets": 1,
                        "overs": 7.6,
                      },
                    },
                  },
                },
              ],
            },
          },
        ],
      },
      {
        "matchType": "Women",
        "seriesMatches": [
          {
            "seriesAdWrapper": {
              "seriesId": 10009,
              "seriesName": "ICC Womens World Cup 2025",
              "matches": [
                {
                  "matchInfo": {
                    "matchId": 121670,
                    "seriesId": 10009,
                    "seriesName": "ICC Womens World Cup 2025",
                    "matchDesc": "2nd Semi-Final",
                    "matchFormat": "ODI",
                    "startDate": "1761816600000",
                    "endDate": "1761845400000",
                    "state": "Complete",
                    "status": "India Women won by 5 wkts",
                    "team1": {
                      "teamId": 100,
                      "teamName": "Australia Women",
                      "teamSName": "AUSW",
                      "imageId": 776205,
                    },
                    "team2": {
                      "teamId": 97,
                      "teamName": "India Women",
                      "teamSName": "INDW",
                      "imageId": 776182,
                    },
                    "venueInfo": {
                      "id": 132,
                      "ground": "Dr DY Patil Sports Academy",
                      "city": "Navi Mumbai ",
                      "timezone": "+05:30",
                      "latitude": "19.042188",
                      "longitude": "73.02671",
                    },
                    "currBatTeamId": 97,
                    "seriesStartDt": "1759190400000",
                    "seriesEndDt": "1762214400000",
                    "isTimeAnnounced": true,
                    "stateTitle": "Complete",
                  },
                  "matchScore": {
                    "team1Score": {
                      "inngs1": {
                        "inningsId": 1,
                        "runs": 338,
                        "wickets": 10,
                        "overs": 49.5,
                      },
                    },
                    "team2Score": {
                      "inngs1": {
                        "inningsId": 2,
                        "runs": 341,
                        "wickets": 5,
                        "overs": 48.3,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            "ad": {
              "name": "native_matches",
              "layout": "native_large",
              "position": 4,
            },
          },
        ],
      },
    ],
    "filters": {
      "matchType": ["International", "League", "Domestic", "Women"],
    },
    "appIndex": {
      "seoTitle": "Live Cricket Score - Scorecard and Match Results",
      "webURL": "www.cricbuzz.com/live-cricket-scores/",
    },
    "responseLastUpdated": "1761844986",
  });
  static final String scorecard = jsonEncode({
    "scorecard": [
      {
        "inningsid": 1,
        "batsman": [
          {
            "id": 9113,
            "balls": 15,
            "runs": 5,
            "fours": 0,
            "sixes": 0,
            "strkrate": "33.33",
            "name": "Alyssa Healy",
            "nickname": "",
            "iscaptain": true,
            "iskeeper": true,
            "outdec": "b Kranti Gaud",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 15636,
            "balls": 93,
            "runs": 119,
            "fours": 17,
            "sixes": 3,
            "strkrate": "127.96",
            "name": "Phoebe Litchfield",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "b Amanjot Kaur",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 9115,
            "balls": 88,
            "runs": 77,
            "fours": 6,
            "sixes": 2,
            "strkrate": "87.5",
            "name": "Ellyse Perry",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "b Radha Yadav",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 9989,
            "balls": 22,
            "runs": 24,
            "fours": 3,
            "sixes": 0,
            "strkrate": "109.09",
            "name": "Beth Mooney",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c Jemimah Rodrigues b Shree Charani",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 12211,
            "balls": 6,
            "runs": 3,
            "fours": 0,
            "sixes": 0,
            "strkrate": "50",
            "name": "Annabel Sutherland",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c and b Shree Charani",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11989,
            "balls": 45,
            "runs": 63,
            "fours": 4,
            "sixes": 4,
            "strkrate": "140",
            "name": "Ashleigh Gardner",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "run out (Kranti Gaud/Richa Ghosh)",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11956,
            "balls": 7,
            "runs": 12,
            "fours": 2,
            "sixes": 0,
            "strkrate": "171.43",
            "name": "Tahlia McGrath",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "run out (Jemimah Rodrigues/Richa Ghosh)",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 9476,
            "balls": 17,
            "runs": 17,
            "fours": 0,
            "sixes": 0,
            "strkrate": "100",
            "name": "Kim Garth",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "run out (Amanjot Kaur/Richa Ghosh)",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 12002,
            "balls": 4,
            "runs": 4,
            "fours": 1,
            "sixes": 0,
            "strkrate": "100",
            "name": "Alana King",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c Richa Ghosh b Deepti Sharma",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 12011,
            "balls": 1,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Sophie Molineux",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "b Deepti Sharma",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 9108,
            "balls": 1,
            "runs": 1,
            "fours": 0,
            "sixes": 0,
            "strkrate": "100",
            "name": "Megan Schutt",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "not out",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
        ],
        "bowler": [
          {
            "id": 14491,
            "overs": "8",
            "maidens": 0,
            "wickets": 0,
            "runs": 39,
            "economy": "4.9",
            "name": "Renuka Singh",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 80,
            "rpb": 0.49,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 1448841,
            "overs": "6",
            "maidens": 0,
            "wickets": 1,
            "runs": 58,
            "economy": "9.7",
            "name": "Kranti Gaud",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 60,
            "rpb": 0.97,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 41078,
            "overs": "10",
            "maidens": 0,
            "wickets": 2,
            "runs": 49,
            "economy": "4.9",
            "name": "Shree Charani",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 100,
            "rpb": 0.49,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11098,
            "overs": "9.5",
            "maidens": 0,
            "wickets": 2,
            "runs": 73,
            "economy": "7.4",
            "name": "Deepti Sharma",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 95,
            "rpb": 0.77,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 22226,
            "overs": "8",
            "maidens": 0,
            "wickets": 1,
            "runs": 51,
            "economy": "6.4",
            "name": "Amanjot Kaur",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 80,
            "rpb": 0.64,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13533,
            "overs": "8",
            "maidens": 0,
            "wickets": 1,
            "runs": 66,
            "economy": "8.2",
            "name": "Radha Yadav",
            "nickname": "",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 80,
            "rpb": 0.82,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
        ],
        "fow": {
          "fow": [
            {
              "batsmanid": 9113,
              "batsmanname": "Alyssa Healy",
              "overnbr": 5.1,
              "runs": 25,
              "ballnbr": 31,
            },
            {
              "batsmanid": 15636,
              "batsmanname": "Phoebe Litchfield",
              "overnbr": 27.2,
              "runs": 180,
              "ballnbr": 164,
            },
            {
              "batsmanid": 9989,
              "batsmanname": "Beth Mooney",
              "overnbr": 33.6,
              "runs": 220,
              "ballnbr": 204,
            },
            {
              "batsmanid": 12211,
              "batsmanname": "Annabel Sutherland",
              "overnbr": 35.5,
              "runs": 228,
              "ballnbr": 215,
            },
            {
              "batsmanid": 9115,
              "batsmanname": "Ellyse Perry",
              "overnbr": 39.2,
              "runs": 243,
              "ballnbr": 236,
            },
            {
              "batsmanid": 11956,
              "batsmanname": "Tahlia McGrath",
              "overnbr": 41.4,
              "runs": 265,
              "ballnbr": 250,
            },
            {
              "batsmanid": 11989,
              "batsmanname": "Ashleigh Gardner",
              "overnbr": 48.3,
              "runs": 331,
              "ballnbr": 291,
            },
            {
              "batsmanid": 12002,
              "batsmanname": "Alana King",
              "overnbr": 49.2,
              "runs": 336,
              "ballnbr": 296,
            },
            {
              "batsmanid": 12011,
              "batsmanname": "Sophie Molineux",
              "overnbr": 49.3,
              "runs": 336,
              "ballnbr": 297,
            },
            {
              "batsmanid": 9476,
              "batsmanname": "Kim Garth",
              "overnbr": 49.5,
              "runs": 338,
              "ballnbr": 299,
            },
          ],
        },
        "extras": {
          "legbyes": 2,
          "byes": 0,
          "wides": 11,
          "noballs": 0,
          "penalty": 0,
          "total": 13,
        },
        "score": 338,
        "wickets": 10,
        "overs": 49.5,
        "runrate": 6.78,
        "batteamname": "Australia Women",
        "batteamsname": "AUSW",
        "isdeclared": false,
        "isfollowon": false,
        "ballnbr": 299,
        "rpb": 1.13,
        "partnership": {
          "partnership": [
            {
              "id": 0,
              "bat1id": 9113,
              "bat1name": "Healy",
              "bat1runs": 5,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 15636,
              "bat2name": "Phoebe Litchfield",
              "bat2runs": 17,
              "bat2fours": 4,
              "bat2sixes": 0,
              "totalruns": 25,
              "totalballs": 31,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9115,
              "bat1name": "Perry",
              "bat1runs": 45,
              "bat1fours": 5,
              "bat1sixes": 1,
              "bat2id": 15636,
              "bat2name": "Phoebe Litchfield",
              "bat2runs": 102,
              "bat2fours": 13,
              "bat2sixes": 3,
              "totalruns": 155,
              "totalballs": 133,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9115,
              "bat1name": "Perry",
              "bat1runs": 16,
              "bat1fours": 0,
              "bat1sixes": 1,
              "bat2id": 9989,
              "bat2name": "Mooney",
              "bat2runs": 24,
              "bat2fours": 3,
              "bat2sixes": 0,
              "totalruns": 40,
              "totalballs": 40,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9115,
              "bat1name": "Perry",
              "bat1runs": 5,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 12211,
              "bat2name": "Sutherland",
              "bat2runs": 3,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 8,
              "totalballs": 11,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9115,
              "bat1name": "Perry",
              "bat1runs": 11,
              "bat1fours": 1,
              "bat1sixes": 0,
              "bat2id": 11989,
              "bat2name": "Gardner",
              "bat2runs": 4,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 15,
              "totalballs": 21,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 11956,
              "bat1name": "McGrath",
              "bat1runs": 12,
              "bat1fours": 2,
              "bat1sixes": 0,
              "bat2id": 11989,
              "bat2name": "Gardner",
              "bat2runs": 9,
              "bat2fours": 2,
              "bat2sixes": 0,
              "totalruns": 22,
              "totalballs": 14,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9476,
              "bat1name": "Kim Garth",
              "bat1runs": 15,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 11989,
              "bat2name": "Gardner",
              "bat2runs": 50,
              "bat2fours": 2,
              "bat2sixes": 4,
              "totalruns": 66,
              "totalballs": 41,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9476,
              "bat1name": "Kim Garth",
              "bat1runs": 1,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 12002,
              "bat2name": "Alana King",
              "bat2runs": 4,
              "bat2fours": 1,
              "bat2sixes": 0,
              "totalruns": 5,
              "totalballs": 5,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9476,
              "bat1name": "Kim Garth",
              "bat1runs": 0,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 12011,
              "bat2name": "Molineux",
              "bat2runs": 0,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 0,
              "totalballs": 1,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 9476,
              "bat1name": "Kim Garth",
              "bat1runs": 0,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 9108,
              "bat2name": "Schutt",
              "bat2runs": 1,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 1,
              "totalballs": 2,
              "bat1balls": 0,
              "bat2balls": 0,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 0,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 0,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
          ],
        },
      },
      {
        "inningsid": 2,
        "batsman": [
          {
            "id": 14825,
            "balls": 5,
            "runs": 10,
            "fours": 2,
            "sixes": 0,
            "strkrate": "200",
            "name": "Shafali Verma",
            "nickname": "Shafali Verma",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "lbw b Kim Garth",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 10012,
            "balls": 24,
            "runs": 24,
            "fours": 2,
            "sixes": 1,
            "strkrate": "100",
            "name": "Smriti Mandhana",
            "nickname": "Smriti Mandhana",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "c Alyssa Healy b Kim Garth",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13517,
            "balls": 131,
            "runs": 118,
            "fours": 12,
            "sixes": 0,
            "strkrate": "90.08",
            "name": "Jemimah Rodrigues",
            "nickname": "Jemimah Rodrigues",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "batting",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 9082,
            "balls": 88,
            "runs": 89,
            "fours": 10,
            "sixes": 2,
            "strkrate": "101.14",
            "name": "Harmanpreet Kaur",
            "nickname": "Harmanpreet Kaur",
            "iscaptain": true,
            "iskeeper": false,
            "outdec": "c Ashleigh Gardner b Annabel Sutherland",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11098,
            "balls": 17,
            "runs": 24,
            "fours": 3,
            "sixes": 0,
            "strkrate": "141.18",
            "name": "Deepti Sharma",
            "nickname": "Deepti Sharma",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "run out (Kim Garth/Alyssa Healy)",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 16208,
            "balls": 16,
            "runs": 26,
            "fours": 2,
            "sixes": 2,
            "strkrate": "162.5",
            "name": "Richa Ghosh",
            "nickname": "Richa Ghosh",
            "iscaptain": false,
            "iskeeper": true,
            "outdec": "c Kim Garth b Annabel Sutherland",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 22226,
            "balls": 2,
            "runs": 1,
            "fours": 0,
            "sixes": 0,
            "strkrate": "50",
            "name": "Amanjot Kaur",
            "nickname": "Amanjot Kaur",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "batting",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 13533,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Radha Yadav",
            "nickname": "Radha Yadav",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 1448841,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Kranti Gaud",
            "nickname": "Kranti Gaud",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 41078,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Shree Charani",
            "nickname": "Shree Charani",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 14491,
            "balls": 0,
            "runs": 0,
            "fours": 0,
            "sixes": 0,
            "strkrate": "0",
            "name": "Renuka Singh Thakur",
            "nickname": "Renuka Singh",
            "iscaptain": false,
            "iskeeper": false,
            "outdec": "",
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "iscbplusfree": false,
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
        ],
        "bowler": [
          {
            "id": 9108,
            "overs": "6",
            "maidens": 0,
            "wickets": 0,
            "runs": 40,
            "economy": "6.7",
            "name": "Megan Schutt",
            "nickname": "Megan Schutt",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 60,
            "rpb": 0.67,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 9476,
            "overs": "7",
            "maidens": 0,
            "wickets": 2,
            "runs": 46,
            "economy": "6.6",
            "name": "Kim Garth",
            "nickname": "Kim Garth",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 70,
            "rpb": 0.66,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11989,
            "overs": "8",
            "maidens": 0,
            "wickets": 0,
            "runs": 55,
            "economy": "6.9",
            "name": "Ashleigh Gardner",
            "nickname": "Ashleigh Gardner",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 80,
            "rpb": 0.69,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 12011,
            "overs": "6",
            "maidens": 0,
            "wickets": 0,
            "runs": 34,
            "economy": "5.7",
            "name": "Sophie Molineux",
            "nickname": "Sophie Molineux",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 60,
            "rpb": 0.57,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "IN",
          },
          {
            "id": 12211,
            "overs": "9",
            "maidens": 0,
            "wickets": 2,
            "runs": 54,
            "economy": "6",
            "name": "Annabel Sutherland",
            "nickname": "Annabel Sutherland",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 90,
            "rpb": 0.6,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 12002,
            "overs": "9",
            "maidens": 0,
            "wickets": 0,
            "runs": 58,
            "economy": "6.4",
            "name": "Alana King",
            "nickname": "Alana King",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 90,
            "rpb": 0.64,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
          {
            "id": 11956,
            "overs": "2",
            "maidens": 0,
            "wickets": 0,
            "runs": 19,
            "economy": "9.5",
            "name": "Tahlia McGrath",
            "nickname": "Tahlia McGrath",
            "iscaptain": false,
            "iskeeper": false,
            "videotype": "",
            "videourl": "",
            "videoid": 0,
            "dots": 0,
            "balls": 20,
            "rpb": 0.95,
            "planid": 0,
            "imageid": 0,
            "premiumvideourl": "",
            "ispremiumfree": false,
            "inmatchchange": "",
            "isoverseas": false,
            "playingxichange": "",
          },
        ],
        "fow": {
          "fow": [
            {
              "batsmanid": 14825,
              "batsmanname": "Shafali Verma",
              "overnbr": 1.3,
              "runs": 13,
              "ballnbr": 9,
            },
            {
              "batsmanid": 10012,
              "batsmanname": "Smriti Mandhana",
              "overnbr": 9.2,
              "runs": 59,
              "ballnbr": 56,
            },
            {
              "batsmanid": 9082,
              "batsmanname": "Harmanpreet Kaur",
              "overnbr": 35.2,
              "runs": 226,
              "ballnbr": 212,
            },
            {
              "batsmanid": 11098,
              "batsmanname": "Deepti Sharma",
              "overnbr": 40.5,
              "runs": 264,
              "ballnbr": 245,
            },
            {
              "batsmanid": 16208,
              "batsmanname": "Richa Ghosh",
              "overnbr": 45.6,
              "runs": 310,
              "ballnbr": 276,
            },
          ],
        },
        "extras": {
          "legbyes": 6,
          "byes": 4,
          "wides": 13,
          "noballs": 1,
          "penalty": 0,
          "total": 24,
        },
        "score": 316,
        "wickets": 5,
        "overs": 47.0,
        "runrate": 6.72,
        "batteamname": "India Women",
        "batteamsname": "INDW",
        "isdeclared": false,
        "isfollowon": false,
        "ballnbr": 282,
        "rpb": 1.12,
        "partnership": {
          "partnership": [
            {
              "id": 0,
              "bat1id": 14825,
              "bat1name": "Shafali Verma",
              "bat1runs": 10,
              "bat1fours": 2,
              "bat1sixes": 0,
              "bat2id": 10012,
              "bat2name": "Smriti",
              "bat2runs": 3,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 13,
              "totalballs": 9,
              "bat1balls": 5,
              "bat2balls": 4,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 2,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 2,
              "bat1sixers": 0,
              "bat2ones": 3,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 13517,
              "bat1name": "Rodrigues",
              "bat1runs": 19,
              "bat1fours": 3,
              "bat1sixes": 0,
              "bat2id": 10012,
              "bat2name": "Smriti",
              "bat2runs": 21,
              "bat2fours": 2,
              "bat2sixes": 1,
              "totalruns": 46,
              "totalballs": 47,
              "bat1balls": 27,
              "bat2balls": 20,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 1,
              "bat1twos": 3,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 3,
              "bat1sixers": 0,
              "bat2ones": 5,
              "bat2twos": 1,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 2,
              "bat2sixers": 1,
            },
            {
              "id": 0,
              "bat1id": 13517,
              "bat1name": "Rodrigues",
              "bat1runs": 66,
              "bat1fours": 7,
              "bat1sixes": 0,
              "bat2id": 9082,
              "bat2name": "Kaur",
              "bat2runs": 89,
              "bat2fours": 10,
              "bat2sixes": 2,
              "totalruns": 167,
              "totalballs": 156,
              "bat1balls": 68,
              "bat2balls": 88,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 32,
              "bat1twos": 3,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 7,
              "bat1sixers": 0,
              "bat2ones": 33,
              "bat2twos": 2,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 10,
              "bat2sixers": 2,
            },
            {
              "id": 0,
              "bat1id": 13517,
              "bat1name": "Rodrigues",
              "bat1runs": 11,
              "bat1fours": 0,
              "bat1sixes": 0,
              "bat2id": 11098,
              "bat2name": "Deepti Sharma",
              "bat2runs": 24,
              "bat2fours": 3,
              "bat2sixes": 0,
              "totalruns": 38,
              "totalballs": 33,
              "bat1balls": 17,
              "bat2balls": 17,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 11,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 0,
              "bat1sixers": 0,
              "bat2ones": 12,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 3,
              "bat2sixers": 0,
            },
            {
              "id": 0,
              "bat1id": 13517,
              "bat1name": "Rodrigues",
              "bat1runs": 17,
              "bat1fours": 1,
              "bat1sixes": 0,
              "bat2id": 16208,
              "bat2name": "Richa Ghosh",
              "bat2runs": 26,
              "bat2fours": 2,
              "bat2sixes": 2,
              "totalruns": 46,
              "totalballs": 31,
              "bat1balls": 15,
              "bat2balls": 16,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 11,
              "bat1twos": 1,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 1,
              "bat1sixers": 0,
              "bat2ones": 6,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 2,
              "bat2sixers": 2,
            },
            {
              "id": 0,
              "bat1id": 13517,
              "bat1name": "Rodrigues",
              "bat1runs": 5,
              "bat1fours": 1,
              "bat1sixes": 0,
              "bat2id": 22226,
              "bat2name": "Amanjot Kaur",
              "bat2runs": 1,
              "bat2fours": 0,
              "bat2sixes": 0,
              "totalruns": 6,
              "totalballs": 6,
              "bat1balls": 4,
              "bat2balls": 2,
              "teamname": "",
              "teamid": 0,
              "bat1ones": 1,
              "bat1twos": 0,
              "bat1threes": 0,
              "bat1fives": 0,
              "bat1boundaries": 1,
              "bat1sixers": 0,
              "bat2ones": 1,
              "bat2twos": 0,
              "bat2threes": 0,
              "bat2fives": 0,
              "bat2boundaries": 0,
              "bat2sixers": 0,
            },
          ],
        },
      },
    ],
    "ismatchcomplete": false,
    "appindex": {
      "seotitle":
          "Cricket scorecard - AUSW vs INDW 2nd Semi-Final,ICC Womens World Cup 2025 | Cricbuzz.com",
      "weburl":
          "http://www.cricbuzz.com/live-cricket-scorecard/121670/ausw-vs-indw-2nd-semi-final-icc-womens-world-cup-2025",
    },
    "status": "India Women need 23 runs in 18 balls",
    "responselastupdated": 1761843905,
  });

  static final String matchInfo = jsonEncode({
    "matchid": 117362,
    "seriesid": 9629,
    "seriesname": "West Indies tour of India, 2025",
    "matchdesc": "2nd Test",
    "matchformat": "TEST",
    "startdate": 1760068800000,
    "enddate": 1760439600000,
    "state": "Stumps",
    "status": "Day 2: Stumps",
    "team1": {
      "teamid": 2,
      "teamname": "India",
      "teamsname": "IND",
      "isfullmember": false,
      "isassociated": false,
      "isleagueteam": false,
      "iswomenteam": false,
      "isheader": false,
      "isactive": false,
      "teampriority": "",
      "isvideopresent": false,
      "imageid": 0,
      "countryname": "",
      "belongsto": "",
    },
    "team2": {
      "teamid": 10,
      "teamname": "West Indies",
      "teamsname": "WI",
      "isfullmember": false,
      "isassociated": false,
      "isleagueteam": false,
      "iswomenteam": false,
      "isheader": false,
      "isactive": false,
      "teampriority": "",
      "isvideopresent": false,
      "imageid": 0,
      "countryname": "",
      "belongsto": "",
    },
    "umpire1": {"id": 4730, "name": "Paul Reiffel", "country": "AUS"},
    "umpire2": {"id": 5398, "name": "Richard Illingworth", "country": "ENG"},
    "umpire3": {"id": 5475, "name": "Alex Wharf", "country": "ENG"},
    "referee": {"id": 3395, "name": "Andy Pycroft", "country": "ZIM"},
    "venueinfo": {
      "id": 51,
      "ground": "Arun Jaitley Stadium",
      "city": "Delhi",
      "country": "India",
      "timezone": "+05:30",
      "established": 1883,
      "capacity": "48000",
      "knownas": "",
      "ends": "Stadium End, Pavilion End",
      "hometeam": "Delhi, Delhi Capitals",
      "floodlights": false,
      "curator": "",
      "profile": "",
      "imageurl": "",
      "groundlength": 0.0,
      "groundwidth": 0.0,
      "othersports": "",
      "imageid": "",
      "latitude": "",
      "longitude": "",
    },
    "currbatteamid": 0,
    "ismatchnotcovered": false,
    "appindex": {
      "seotitle":
          "Cricket match facts IND vs WI 2nd Test,West Indies tour of India, 2025 | Cricbuzz.com",
      "weburl":
          "http://www.cricbuzz.com/cricket-match-facts/117362/ind-vs-wi-2nd-test-west-indies-tour-of-india-2025",
    },
    "istournament": false,
    "tossstatus": "India opt to bat",
    "seriesstartdt": 1759276800000,
    "seriesenddt": 1760486400000,
    "istimeannounced": false,
    "statetitle": "",
    "replacematchid": 0,
    "livestreamenabled": false,
    "isfantasyenabled": false,
    "broadcastinfo": [
      {
        "country": "IN",
        "broadcaster": [
          {"broadcasttype": "Streaming", "value": "JioHotstar"},
          {"broadcasttype": "TV", "value": "Star Sports Network"},
        ],
      },
    ],
    "daynight": false,
    "matchtype": "International",
    "seriestype": "",
    "shortstatus": "Stump",
    "boundarytrackervalues": {"boundarytrackervalue": []},
    "matchimageid": 769236,
    "islivestreamenabled": false,
    "isfantasyhandbookenabled": false,
  });
}
